"""
GET /api/projects/{project_id}/score

Returns the benchmark score artifact produced by the BenchmarkScoreNode
during the VALIDATION phase. The score is stored in the artifacts table
with agent_name = 'Benchmark Scorer' and artifact_type = 'validation_report'.
"""
from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_user
from app.core.database import get_db
from app.models.artifact import Artifact
from app.models.phase import Phase, PhaseType
from app.models.project import Project
from app.models.user import User

router = APIRouter()


# ── Response schemas ──────────────────────────────────────────────────────────

class DimensionScore(BaseModel):
    score: float
    rationale: str


class BenchmarkScoreResponse(BaseModel):
    project_id: uuid.UUID
    phase_id: uuid.UUID
    overall_score: float
    percentile_estimate: int
    verdict: str
    one_line_summary: str
    biggest_strength: str
    biggest_risk: str
    dimensions: dict[str, DimensionScore]
    markdown_content: str | None = None


# ── Route ─────────────────────────────────────────────────────────────────────

@router.get("/{project_id}/score", response_model=BenchmarkScoreResponse)
async def get_benchmark_score(
    project_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Returns the latest benchmark score for a project.
    Score is generated by the BenchmarkScoreNode at the end of the VALIDATION phase.
    Returns 404 if validation has not been run or score is not yet available.
    """
    # Verify project ownership
    project_result = await db.execute(
        select(Project).where(
            Project.id == project_id,
            Project.user_id == current_user.id,
        )
    )
    project = project_result.scalar_one_or_none()
    if not project:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Project not found",
        )

    # Find the most recent VALIDATION phase
    phase_result = await db.execute(
        select(Phase)
        .where(
            Phase.project_id == project_id,
            Phase.phase_type == PhaseType.VALIDATION,
        )
        .order_by(Phase.created_at.desc())
        .limit(1)
    )
    phase = phase_result.scalar_one_or_none()
    if not phase:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Validation phase has not been run for this project",
        )

    # Find the benchmark score artifact from that phase
    artifact_result = await db.execute(
        select(Artifact)
        .where(
            Artifact.phase_id == phase.id,
            Artifact.agent_name == "Benchmark Scorer",
        )
        .order_by(Artifact.created_at.desc())
        .limit(1)
    )
    artifact = artifact_result.scalar_one_or_none()
    if not artifact:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Benchmark score not yet available. Run the validation phase to generate it.",
        )

    # Parse the JSONB content
    raw: dict = artifact.content if isinstance(artifact.content, dict) else {}

    # Handle graceful fallback if JSON parsing failed during generation
    if raw.get("parse_error") or not raw.get("dimensions"):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Benchmark score data is malformed. Re-running validation will fix this.",
        )

    raw_dims: dict = raw.get("dimensions", {})
    dimensions: dict[str, DimensionScore] = {}
    for key, val in raw_dims.items():
        if isinstance(val, dict) and "score" in val:
            dimensions[key] = DimensionScore(
                score=float(val.get("score", 0)),
                rationale=str(val.get("rationale", "")),
            )

    return BenchmarkScoreResponse(
        project_id=project_id,
        phase_id=phase.id,
        overall_score=float(raw.get("overall_score", 0)),
        percentile_estimate=int(raw.get("percentile_estimate", 0)),
        verdict=str(raw.get("verdict", "Unknown")),
        one_line_summary=str(raw.get("one_line_summary", "")),
        biggest_strength=str(raw.get("biggest_strength", "")),
        biggest_risk=str(raw.get("biggest_risk", "")),
        dimensions=dimensions,
        markdown_content=artifact.markdown_content,
    )
