"""add landing_page phase and tables

Revision ID: 3376ab438d30
Revises: a54f1e1f77c9
Create Date: 2026-03-28 19:30:00.461648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '3376ab438d30'
down_revision: Union[str, None] = 'a54f1e1f77c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'landing_pages' not in existing_tables:
        op.create_table('landing_pages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('html', sa.Text(), nullable=False),
        sa.Column('page_title', sa.String(length=255), nullable=False),
        sa.Column('meta_description', sa.String(length=500), nullable=False),
        sa.Column('is_published', sa.Boolean(), nullable=False),
        sa.Column('view_count', sa.Integer(), nullable=False),
        sa.Column('template_style', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_landing_pages_project_id'), 'landing_pages', ['project_id'], unique=True)
        op.create_index(op.f('ix_landing_pages_slug'), 'landing_pages', ['slug'], unique=True)
        
    if 'landing_page_leads' not in existing_tables:
        op.create_table('landing_page_leads',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('landing_page_id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('source', sa.String(length=100), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['landing_page_id'], ['landing_pages.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_landing_page_leads_landing_page_id'), 'landing_page_leads', ['landing_page_id'], unique=False)
        op.create_index(op.f('ix_landing_page_leads_project_id'), 'landing_page_leads', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_page_leads_project_id'), table_name='landing_page_leads')
    op.drop_index(op.f('ix_landing_page_leads_landing_page_id'), table_name='landing_page_leads')
    op.drop_table('landing_page_leads')
    op.drop_index(op.f('ix_landing_pages_slug'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_project_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    # ### end Alembic commands ###
